version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10  # or your preferred Python version
    working_directory: ~/repo

jobs:
  run-tests:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -e . -r requirements.txt
      - run:
          name: Run tests
          command: |
            curl -X POST -H 'Content-type: application/json' \--data '{"text":"Hello, World!"}' $SLACK_WEBHOOK
            pwd
            ls -la
            source venv/bin/activate
            python -m unittest
# https://hooks.slack.com/services/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
workflows:
  version: 2
  test:
    jobs:
      - run-tests