version: 2.1

commands:
  notify_slack:
    parameters:
      title:
        type: string
      color:
        type: string
        default: "#36a64f"
    steps:
      - run:
          name: Send Slack Notification
          command: |
            curl -X POST -H 'Content-type: application/json' --data '{
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "plain_text",
                    "text": "<< parameters.title >>"
                  }
                }
              ],
              "attachments": [
                {
                  "color": "<< parameters.color >>",
                  "fields": [
                    {
                      "title": "Branch",
                      "value": "'"$CIRCLE_BRANCH"'",
                      "short": false
                    },
                    {
                      "title": "Commit",
                      "value": "'"${CIRCLE_SHA1:0:7}"'",
                      "short": true
                    }
                  ]
                }
              ]
            }' $SLACK_WEBHOOK

executors:
  python-executor:
    docker:
      - image: cimg/python:3.10  # or your preferred Python version
    working_directory: ~/repo

jobs:
  run-tests:
    executor: python-executor
    steps:
      - notify_slack:
          title: "Build starting..."
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            source venv/bin/activate
            pip install -e . -r requirements.txt
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            python -m unittest
      - run:
          name: Notify Slack on Success
          when: on_success
          command: |
            COMMIT_MESSAGE=$(git log -1 --pretty=%B $CIRCLE_SHA1)
            COMMIT_AUTHOR=$(git log -1 --pretty=%an $CIRCLE_SHA1)
            COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae $CIRCLE_SHA1)
            COMMIT_DATE=$(git log -1 --pretty=%cd $CIRCLE_SHA1)
            SHORT_COMMIT_HASH=$(git rev-parse --short $CIRCLE_SHA1)
            COMMIT_SUBJECT=$(git log -1 --pretty=%s $CIRCLE_SHA1)
            
            curl -X POST -H 'Content-type: application/json' --data "{
              \"channel\": \"#deployments\",
              \"username\": \"CircleCI Bot\",
              \"icon_emoji\": \":tada:\",
              \"text\": \"Build Succeeded! \n
              GitHub Message: $COMMIT_MESSAGE \n
              Author: $COMMIT_AUTHOR \n
              Author Email: $COMMIT_AUTHOR_EMAIL \n
              Commit Date: $COMMIT_DATE \n
              Short Commit Hash: $SHORT_COMMIT_HASH \n
              Commit Subject: $COMMIT_SUBJECT \n
              Branch: $CIRCLE_BRANCH \n
              Build Number: $CIRCLE_BUILD_NUM \n
              Build URL: $CIRCLE_BUILD_URL \n
              Project Repository: $CIRCLE_PROJECT_REPONAME \n
              Project Username: $CIRCLE_PROJECT_USERNAME \"
            }" $SLACK_WEBHOOK
      - run:
          name: Notify Slack on Failure
          when: on_fail
          command: |
            COMMIT_MESSAGE=$(git log -1 --pretty=%B $CIRCLE_SHA1)
            COMMIT_AUTHOR=$(git log -1 --pretty=%an $CIRCLE_SHA1)
            COMMIT_AUTHOR_EMAIL=$(git log -1 --pretty=%ae $CIRCLE_SHA1)
            COMMIT_DATE=$(git log -1 --pretty=%cd $CIRCLE_SHA1)
            SHORT_COMMIT_HASH=$(git rev-parse --short $CIRCLE_SHA1)
            COMMIT_SUBJECT=$(git log -1 --pretty=%s $CIRCLE_SHA1)
            
            curl -X POST -H 'Content-type: application/json' --data "{
              \"channel\": \"#deployments\",
              \"username\": \"CircleCI Bot\",
              \"icon_emoji\": \"rotating_light\",
              \"text\": \"Build Failed! \n
            GitHub Message: $COMMIT_MESSAGE \n
            Author: $COMMIT_AUTHOR \n
            Author Email: $COMMIT_AUTHOR_EMAIL \n
            Commit Date: $COMMIT_DATE \n
            Short Commit Hash: $SHORT_COMMIT_HASH \n
            Commit Subject: $COMMIT_SUBJECT \n
            Branch: $CIRCLE_BRANCH \n
            Build Number: $CIRCLE_BUILD_NUM \n
            Build URL: $CIRCLE_BUILD_URL \n
            Project Repository: $CIRCLE_PROJECT_REPONAME \n
            Project Username: $CIRCLE_PROJECT_USERNAME \"
            }" $SLACK_WEBHOOK
workflows:
  version: 2
  test-workflow:
    jobs:
      - run-tests:
          filters:
            branches:
              only:
                - main